name: xengagement
channels:
  - conda-forge
dependencies:
  - python=3.7
  - dash
  - dash-renderer
  - dash-core-components
  - dash-html-components
  - plotly
  - pandas
  - jupyter-dash
  - pip
  - pip:
    - gunicorn
    - ipython==7.19.0